---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: feira-de-jogos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/feira-de-jogos/feira-de-jogos/frontend:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: feira-de-jogos
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-frontend
  namespace: feira-de-jogos
spec:
  parentRefs:
    - name: gateway-feira-de-jogos
      sectionName: https-feira-de-jogos
  hostnames:
    - "feira-de-jogos.dev.br"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: service-frontend
      port: 80
